name: Publish MSSQLClient Mcp Server to Dockerhub and GitHub Releases

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # Only trigger on tags with format like 1.2.3

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
      - name: Update version in project file
        run: |
          # Extract the version from the tag
          VERSION=${{ steps.get_version.outputs.VERSION }}
          echo "Updating project version to $VERSION"
          
          # Use XML tool to update the version in the project file
          # This updates AssemblyVersion, FileVersion, and Version properties
          sed -i \
            -e "s/<AssemblyVersion>.*<\/AssemblyVersion>/<AssemblyVersion>$VERSION<\/AssemblyVersion>/g" \
            -e "s/<FileVersion>.*<\/FileVersion>/<FileVersion>$VERSION<\/FileVersion>/g" \
            -e "s/<Version>.*<\/Version>/<Version>$VERSION<\/Version>/g" \
            src/Core.Infrastructure.McpServer/Core.Infrastructure.McpServer.csproj
          
          # Show the updated file for verification
          cat src/Core.Infrastructure.McpServer/Core.Infrastructure.McpServer.csproj
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
          
      - name: Build application
        run: dotnet build src/mssqlclient.sln --configuration Release
        
      - name: Create binaries directory
        run: |
          mkdir -p ./bin-output
          cp -r src/Core.Infrastructure.McpServer/bin/Release/net9.0/. ./bin-output/
        
      - name: Create binary zip
        run: |
          cd ./bin-output
          zip -r ../mssqlclient-mcp-server-${{ steps.get_version.outputs.VERSION }}-bin.zip .
          cd ..
      
      - name: Create source zip
        run: |
          # Exclude .git, .github, and other non-source directories
          zip -r mssqlclient-mcp-server-${{ steps.get_version.outputs.VERSION }}-src.zip . \
            -x "*/bin/*" -x "*/obj/*" -x ".git*" -x ".github/*" -x "bin-output/*" \
            -x "*.zip" -x "mssqlclient-mcp-server-*.zip"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src
          file: ./src/Core.Infrastructure.McpServer/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_CONFIGURATION=Release
          tags: |
            aadversteeg/mssqlclient-mcp-server:${{ steps.get_version.outputs.VERSION }}
            aadversteeg/mssqlclient-mcp-server:latest
  
      # Create GitHub release with the zipped artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: MSSQLClient MCP Server ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            mssqlclient-mcp-server-${{ steps.get_version.outputs.VERSION }}-bin.zip
            mssqlclient-mcp-server-${{ steps.get_version.outputs.VERSION }}-src.zip
          generate_release_notes: true
